services:
  db:
    container_name: mindflow
    image: bitnami/postgresql
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=mindflow
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=mindflow_db
    volumes:
      - ./data/pg:/data/postgres

  redis:
    image: redis
    ports:
      - "6379:6379"